SELECT * FROM users;
SELECT * FROM products;
SELECT * FROM orderdetails;
SELECT * FROM orders;
SELECT * FROM staff;
SELECT 'Hello SQL!';
SELECT 'Find' AS 'First','Insight' AS 'Seceond', 'with SQL' AS 'Third';
SELECT 28 + 891;
SELECT 19 * 27 AS 'Reuslt';
SELECT 37 + 172 AS 'PLUS', 25 * 78 AS 'Times', 'I love SQL!' AS 'Reuslt';
SELECT * FROM products LIMIT 3;
SELECT id, name FROM products LIMIT 30;
SELECT * from orderdetails;
SELECT * from users LIMIT 7;
SELECT id, user_id, order_date FROM orders;
SELECT * FROM users;
SELECT * FROM users WHERE country = 'Korea' and is_marketing_agree = 1;
SELECT * from users WHERE country != 'Korea';
SELECT * from users WHERE country = 'Korea' AND id = 10;
SELECT * FROM users WHERE created_at BETWEEN '2010-12-01' AND '2011-01-01';
SELECT * FROM users WHERE created_at >= '2010-12-01';
SELECT * FROM users WHERE created_at >= '2010-12-01' AND created_at <= '2011-03-01';
SELECT * FROM users WHERE country = 'Korea' OR country = 'USA' OR country = 'UK'; 
SELECT * FROM users WHERE country IN ('Korea', 'USA', 'UK');
SELECT * FROM users WHERE country NOT IN ('Korea', 'USA', 'UK');
SELECT * FROM users WHERE country LIKE 'S%';
SELECT * FROM users WHERE country LIKE '%A';
SELECT * FROM users WHERE country NOT LIKE 'S%';
SELECT created_at, phone, city, country FROM users WHERE country = 'Mexico';
SELECT *, price - discount_price AS discount_amount FROM products WHERE id <= 20 AND price >= 30;
SELECT * FROM users WHERE country NOT IN ('Korea', 'Canada', 'Belgium');
SELECT id, name, price FROM products WHERE name LIKE 'N%';
SELECT * FROM orders WHERE order_date NOT BETWEEN '2015-07-01' AND '2015-10-31';
SELECT * FROM users ORDER BY id DESC;
SELECT * FROM users ORDER BY created_at ASC;
SELECT * FROM users ORDER BY created_at DESC;
SELECT username, phone, city, country, id FROM users ORDER BY 1 ASC;
SELECT city, id FROM users ORDER BY city DESC, id ASC;
SELECT * FROM products ORDER BY price DESC;
SELECT * FROM orders ORDER BY order_date DESC;
SELECT * FROM orderdetails ORDER BY product_id DESC, quantity ASC;