# SELECT COUNT(*) FROM users;
# SELECT COUNT(*) AS userNum FROM users;
# SELECT COUNT(DISTINCT country) from users;
# SELECT MIN(price) FROM products;
# SELECT MAX(price) FROM products;
# SELECT SUM(price) FROM products;
# SELECT AVG(discount_price) FROM products;
# SELECT ROUND(AVG(discount_price), 2) FROM products;
# SELECT ROUND(AVG(discount_price), 2) AS avgPrice FROM products;
# SELECT SUBSTR(created_at, 1, 10) AS DAY, SUBSTR(created_at, 1, 7) AS MONTH, created_at FROM users;
# SELECT LENGTH(username), username FROM users;
# SELECT SUM(price - discount_price) FROM products;
# SELECT ROUND(AVG(price - discount_price), 2) FROM products WHERE id <= 30;
# SELECT COUNT(DISTINCT username) FROM users WHERE created_at BETWEEN '2010-10-01' AND '2010-12-31';
# SELECT COUNT(DISTINCT id) AS userCount FROM users WHERE LENGTH(username) <= 17;
# SELECT country, COUNT(DISTINCT id) AS uniqueUsercount FROM users GROUP BY country;
# SELECT COUNT(DISTINCT id) AS makertingAgree FROM users WHERE country = 'korea' AND is_marketing_agree = 1;
# SELECT country, is_marketing_agree AS marketingDisagree, COUNT(DISTINCT id) AS makertingAgree FROM users GROUP BY country, is_marketing_agree ORDER BY country ASC, is_marketing_agree DESC; 
# SELECT country, city, COUNT(DISTINCT username) FROM users GROUP BY country, city ORDER BY country, username DESC;
# SELECT SUBSTR(created_at, 1, 7) AS MONTH, COUNT(DISTINCT id) AS userCnt FROM users GROUP BY SUBSTR(created_at, 1, 7) ORDER BY MONTH DESC;
# SELECT COUNT(id) AS userCnt FROM users GROUP BY country, city;
# SELECT country, city, COUNT(id) AS userCnt FROM users GROUP BY country, city;
# SELECT order_id, sum(quantity) AS sumQuantity FROM orderdetails GROUP BY order_id ORDER BY sumQuantity DESC;
# SELECT staff_id, user_id, COUNT(*) AS cnt FROM orders GROUP BY staff_id, user_id ORDER BY staff_id, cnt DESC;
# SELECT COUNT(DISTINCT user_id), SUBSTR(order_date, 1, 7) AS month FROM orders GROUP BY month ORDER BY month ASC;
# SELECT COUNT(DISTINCT id) AS userCnt, country AS cnt FROM users WHERE country IN ('Korea', 'USA', 'France') GROUP BY country;
# SELECT country, COUNT(DISTINCT id) AS userCnt FROM users GROUP BY country HAVING COUNT(DISTINCT id) > 7 ORDER BY 2 DESC;
# SELECT staff_id AS staff, COUNT(*) AS staffOrder, user_id AS userOrder FROM orders GROUP BY staff_id HAVING staffOrder >= 10 AND userOrder <=40;
# SELECT user_id ,COUNT(*) AS orderCount FROM orders GROUP BY user_id HAVING orderCount >= 7 ORDER BY orderCount DESC;
# SELECT country, COUNT(DISTINCT city) AS cityCountry, COUNT(country) AS countryUser FROM users GROUP BY country HAVING cityCountry >=5 AND countryUser >=3 ORDER BY cityCountry DESC, countryUser DESC;
# SELECT country, COUNT(country) AS countryUser FROM users GROUP BY country HAVING country IN ('USA' , 'Brazil' , 'Korea' , 'Argentina' , 'Mexico') AND countryUser >=5 ORDER BY countryUser DESC;
# SELECT * FROM users u INNER JOIN orders o ON u.id = o.user_id ORDER BY u.id;
# SELECT * FROM users u LEFT JOIN orders o ON u.id = o.user_id ORDER BY u.id;
# SELECT u.id, u.created_at, u.username, o.id, o.order_date, o.staff_id FROM users u LEFT JOIN orders o ON u.id = o.user_id ORDER BY u.id;
# SELECT * FROM users u LEFT JOIN orders o ON u.id = o.user_id WHERE o.id IS null ORDER BY u.id;8
# SELECT u.id, u.username, u.phone, od.order_id, od.product_id FROM users u LEFT JOIN orders o ON u.id = o.user_id JOIN orderdetails od ON u.id = od.id;